2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_setup.py:_flush():67] Configure stats pid to 137214
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_setup.py:_flush():67] Loading settings from /home/tiger/.config/wandb/settings
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_setup.py:_flush():67] Loading settings from /opt/tiger/R1-Multimodal-Journey/local_scripts/wandb/settings
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /opt/tiger/R1-Multimodal-Journey/local_scripts/wandb/offline-run-20250221_160726-0fxanjd1/logs/debug.log
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /opt/tiger/R1-Multimodal-Journey/local_scripts/wandb/offline-run-20250221_160726-0fxanjd1/logs/debug-internal.log
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_init.py:init():761] calling init triggers
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-21 16:07:26,647 INFO    MainThread:137214 [wandb_init.py:init():784] starting backend
2025-02-21 16:07:26,856 INFO    MainThread:137214 [wandb_init.py:init():788] sending inform_init request
2025-02-21 16:07:26,860 INFO    MainThread:137214 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-21 16:07:26,860 INFO    MainThread:137214 [wandb_init.py:init():803] backend started and connected
2025-02-21 16:07:26,862 INFO    MainThread:137214 [wandb_init.py:init():896] updated telemetry
2025-02-21 16:07:26,866 INFO    MainThread:137214 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-21 16:07:27,177 INFO    MainThread:137214 [wandb_init.py:init():995] starting run threads in backend
2025-02-21 16:07:27,419 INFO    MainThread:137214 [wandb_run.py:_console_start():2377] atexit reg
2025-02-21 16:07:27,419 INFO    MainThread:137214 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-21 16:07:27,419 INFO    MainThread:137214 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-21 16:07:27,419 INFO    MainThread:137214 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-21 16:07:27,421 INFO    MainThread:137214 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-21 16:07:28,440 WARNING MsgRouterThr:137214 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.local/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.local/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.local/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-21 16:07:28,441 INFO    MsgRouterThr:137214 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
